### ISSUE TITLE
[Bug] No universal font

### ISSUE THREAD

**Issue by flofriday** [NLDev/nulldev#2] opened 2016-10-23 18:12 UTC
Windows (Chrome)

![unbenannt](https://cloud.githubusercontent.com/assets/21206831/19628378/aa3da6ac-995c-11e6-9c60-8fff35d5a415.PNG)

Linux (Chrome)
![screenshot from 2016-10-23 20-07-34](https://cloud.githubusercontent.com/assets/21206831/19628380/bbd13898-995c-11e6-918a-fed4a8097349.png)

As you can see the image looks really ugly on linux ... I think because the font is windows preinstalled and not on linux.

**Comment by FisheyLP** [comment] 2017-01-06 01:38
le strg+c, strg+v with font, then
`@font-face{
    font-family: "font_name";
    src: url('font_name.ttf'),
    url('font_name.eot'); /* IE */
}`

or just make a screenshot and insert as picture

**Comment by NLDev** [comment] 2017-01-21 23:37
/* IE, benutzt eh kein schwein aber egal */
Leider doch... Ich überarbeite die Seite in ein paar tagen...

---

/* No one uses IE anyway */
Unfortunately they do... I will rework the site in a couple days

**Comment by NLDev** [comment] 2017-01-24 13:27
The issue is fixed now. The fallback font is on the server and linked in the CSS. There is still a bug with the centering but I made another issue for that: <a href="https://github.com/NLDev/nulldev/issues/7">#7</a>

**Closed by NLDev** 2017-01-24 13:27 UTC
Labels: bug
